### ISSUE TITLE
Exception error(when I try to create a dlc.rpf, I get this error, what should I do?)

### ISSUE THREAD

**Issue by Evseniy** [DurtyFree/altv-cloth-tool#12] opened 2021-03-29 16:08 UTC
I have the following error:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.Data.PartialStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(Stream stream)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(String fileName)
   at altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:line 244
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 23

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by BaspelOp** [comment] 2021-04-09 11:33
How much clothes did you put in there?

**Comment by DurtyFree** [comment] 2021-04-16 09:16
This is a duplicate of #4

**Closed by DurtyFree** 2021-04-16 09:16 UTC
